In [1]:
import numpy as np

## Datatypes and Attributes

In [67]:
import pandas as pd

In [2]:
#numpy has only one datatype and ie., ndarray

In [27]:
#create array
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [5]:
a1.shape

(3,)

In [6]:
#dimension of an array
a1.ndim

1

In [7]:
a1.dtype

dtype('int32')

In [8]:
#number of elements in an array
a1.size

3

In [9]:
# Create dataframe from numpy array
import pandas as pd
df = pd.DataFrame(a1)
df

0
0  1
1  2
2  3

## Create arrays with numpy

In [10]:
#array with ones
ones = np.ones((2, 4))
ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
#array with zeros
zeros = np.zeros((2, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
#array using range - (start, stop, step)
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [18]:
#create a random array - (start, stop, size)
random_array = np.random.randint(0, 20, size=(2, 4))
random_array

array([[ 8, 12,  7, 10],
       [ 2,  8,  4, 17]])

In [20]:
#other way to create an array using random
random_array2 = np.random.random((4, 3))
random_array2

array([[0.30586931, 0.97550018, 0.72333652],
       [0.23829364, 0.77885567, 0.9784405 ],
       [0.99559852, 0.80139516, 0.55173885],
       [0.84980116, 0.50597334, 0.29552703]])

In [21]:
#one more way using random
random_array3 = np.random.rand(4, 3)
random_array3

array([[0.8646434 , 0.9240444 , 0.42724473],
       [0.63487545, 0.47335717, 0.62295694],
       [0.6098673 , 0.93623985, 0.99206221],
       [0.85207869, 0.61714048, 0.00893907]])

In [28]:
# Using Random seed - the number obtained doesnt change ignoring the number of times we run it
np.random.seed(0)
random_array4 = np.random.rand(4, 3)
random_array4

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492]])

## View array and matrices

In [26]:
#view unique elements
np.unique(random_array4)

array([0.38344152, 0.4236548 , 0.43758721, 0.52889492, 0.54488318,
       0.5488135 , 0.60276338, 0.64589411, 0.71518937, 0.79172504,
       0.891773  , 0.96366276])

In [32]:
random_array4

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492]])

In [36]:
random_array4.shape

(4, 3)

In [29]:
#view elements using index
random_array4[0]

array([0.5488135 , 0.71518937, 0.60276338])

In [37]:
random_array4[:2, :2]

array([[0.5488135 , 0.71518937],
       [0.54488318, 0.4236548 ]])

In [38]:
random_array4[:1, :1]

array([[0.5488135]])

In [39]:
random_array4[:2, :1]

array([[0.5488135 ],
       [0.54488318]])

## Manipulate and compare array

### 1.Arithmetic

In [40]:
a1

array([1, 2, 3])

In [44]:
ones =  np.ones(3)
ones

array([1., 1., 1.])

In [45]:
a1 + ones

array([2., 3., 4.])

In [54]:
np.add(a1, ones)

array([2., 3., 4.])

In [46]:
a1 * ones

array([1., 2., 3.])

In [47]:
a1 - ones

array([0., 1., 2.])

In [48]:
a1/ones

array([1., 2., 3.])

In [50]:
random_array4 / a1

array([[0.5488135 , 0.35759468, 0.20092113],
       [0.54488318, 0.2118274 , 0.21529804],
       [0.43758721, 0.4458865 , 0.32122092],
       [0.38344152, 0.39586252, 0.17629831]])

In [51]:
# floor removes decimals and rounds up the number
random_array4 // a1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [52]:
#power 2
random_array4 ** 2

array([[0.30119626, 0.51149583, 0.36332369],
       [0.29689768, 0.17948339, 0.41717921],
       [0.19148257, 0.79525908, 0.92864592],
       [0.1470274 , 0.62682854, 0.27972984]])

In [53]:
#other way for power
np.square(random_array4)

array([[0.30119626, 0.51149583, 0.36332369],
       [0.29689768, 0.17948339, 0.41717921],
       [0.19148257, 0.79525908, 0.92864592],
       [0.1470274 , 0.62682854, 0.27972984]])

In [55]:
#gives remainder 
random_array4 % 2

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492]])

In [56]:
np.exp(ones)

array([2.71828183, 2.71828183, 2.71828183])

In [57]:
np.log(ones)

array([0., 0., 0.])

### 2.Aggregation

In [58]:
#create python list
py_list = [1, 2, 3]
py_list

[1, 2, 3]

In [59]:
#sum using python method
sum(py_list)

6

### Use Python's methods (sum()) on python datatypes and use Numpy's methods on Numpy arrays (np.sum())

In [62]:
# create a massive numpy array
massive_array = np.random.random(1000)
massive_array[:10]

array([0.2875445 , 0.45670363, 0.02095007, 0.41161551, 0.48945864,
       0.24367788, 0.588639  , 0.75324012, 0.23583422, 0.6204999 ])

In [63]:
#compare between python's and numpy's sum
%timeit sum(massive_array) # Python's sum
%timeit np.sum(massive_array) # Numpy's sum

153 µs ± 5.82 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
4.13 µs ± 35.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [64]:
np.mean(a1)

2.0

In [65]:
np.std(a1)

0.816496580927726

## Example

### Dot product

In [68]:
#Number of jars sold
np.random.seed(0)
sales_amount = np.random.randint(20, size=(5, 3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [69]:
# create a weekly sales DataFrame
weekly_sales = pd.DataFrame(sales_amount, 
                           index=["Mon", "Tue", "Wed", "Thurs", "Fri"],
                           columns=["Mango_candies", "Nut_candies", "Lemon_candies"])
weekly_sales

Cherry  Nuts  Wafers
Mon        12    15       0
Tue         3     3       7
Wed         9    19      18
Thurs       4     6      12
Fri         1     6       7

In [70]:
#Create price array
prices = np.array([15, 25, 20])
prices

array([15, 25, 20])

In [75]:
#create candy_prices DataFrame - here reshape is done to avoid shape error
candy_prices = pd.DataFrame(prices.reshape(1, 3),
                           index=["price"],
                           columns=["Mango_candies", "Nut_candies", "Lemon_candies"])
candy_prices

Mango_candies  Nut_candies  Lemon_candies
price             15           25             20

In [81]:
total_sales = prices.dot(sales_amount.T)
total_sales

array([555, 260, 970, 450, 305])

In [84]:
#create total_sales DataFrame
total_weekly_sales = pd.DataFrame(total_sales,
                                 index=["Mon", "Tue", "Wed", "Thurs", "Fri"],
                                 columns=["price"])
total_weekly_sales

price
Mon      555
Tue      260
Wed      970
Thurs    450
Fri      305

In [86]:
weekly_sales["Total"] = total_weekly_sales
weekly_sales

Cherry  Nuts  Wafers  Total
Mon        12    15       0    555
Tue         3     3       7    260
Wed         9    19      18    970
Thurs       4     6      12    450
Fri         1     6       7    305

## Playing with images

<img src= "Untitled Folder/car-photo.png"/>

In [94]:
#Turn image into numpy array
from matplotlib.image import imread

car = imread("Untitled Folder/car-photo.png")
car

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [96]:
# few attributes of pandas
car.size, car.shape, car.ndim

(991300, (431, 575, 4), 3)