## WorkFlow of Scikit-Learn

In [1]:
import pandas as pd
import numpy as np

## 1. Get the Data

In [2]:
# import dataset
heart_disease = pd.read_csv("heart-disease.csv")

# view data
heart_disease.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [3]:
# to predict whether or not the patient have heart disease, will use all the data except target column to predict target column

In [4]:
# create X(all the feature columns)
X = heart_disease.drop("target", axis=1)

# create y(the target column)
y = heart_disease["target"]

In [6]:
# Split the data into training and test sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y)

# View the data shapes
X_train.shape, X_test.shape, y_test.shape, y_train.shape

((227, 13), (76, 13), (76,), (227,))

## 2. Choose the model/estimator

In [7]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()

## 3. Fit the model to the data and use it to make a prediction

In [8]:
model.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [9]:
# once the model learn the patterns, it can be further used to make predictions usin predict() function

In [10]:
# make predictions
y_preds = model.predict(X_test)

In [11]:
# this will be in the same format as y test
y_preds

array([0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [15]:
X_test.loc[4]

age          57.0
sex           0.0
cp            0.0
trestbps    120.0
chol        354.0
fbs           0.0
restecg       1.0
thalach     163.0
exang         1.0
oldpeak       0.6
slope         2.0
ca            0.0
thal          2.0
Name: 4, dtype: float64

In [16]:
heart_disease.loc[4]

age          57.0
sex           0.0
cp            0.0
trestbps    120.0
chol        354.0
fbs           0.0
restecg       1.0
thalach     163.0
exang         1.0
oldpeak       0.6
slope         2.0
ca            0.0
thal          2.0
target        1.0
Name: 4, dtype: float64

In [17]:
# make a prdiction on a single sample (has to be array)
model.predict(np.array(X_test.loc[4]).reshape(1, -1))

array([1], dtype=int64)

## 4. Evaluate the model

In [18]:
# A trained model/estimator can be evaluated by calling the score() function and passing it a collection of data

In [20]:
# On the training set
model.score(X_train, y_train)

1.0

In [21]:
# On the test set (unseen)
model.score(X_test, y_test)

0.8421052631578947

## 5. Experiment to improve (Hyperparameter Tuning)

In [22]:
# Try different numbers of estimators (n_estimators is a hyperparameter you can change)
np.random.seed(57)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accruacy on test set: {model.score(X_test, y_test)}")
    print("")

Trying model with 10 estimators...
Model accruacy on test set: 0.8026315789473685

Trying model with 20 estimators...
Model accruacy on test set: 0.7894736842105263

Trying model with 30 estimators...
Model accruacy on test set: 0.7763157894736842

Trying model with 40 estimators...
Model accruacy on test set: 0.8157894736842105

Trying model with 50 estimators...
Model accruacy on test set: 0.7894736842105263

Trying model with 60 estimators...
Model accruacy on test set: 0.8289473684210527

Trying model with 70 estimators...
Model accruacy on test set: 0.8289473684210527

Trying model with 80 estimators...
Model accruacy on test set: 0.8421052631578947

Trying model with 90 estimators...
Model accruacy on test set: 0.7894736842105263



In [24]:
from sklearn.model_selection import cross_val_score

# Try different numbers of estimators with cross-validation and no cross-validation
np.random.seed(22)
for i in range(10, 100, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accruacy on test set: {model.score(X_test, y_test)}")
    print(f"Cross-validation score: {np.mean(cross_val_score(model, X, y, cv=5)) * 100}%")
    print("")

Trying model with 10 estimators...
Model accruacy on test set: 0.7368421052631579
Cross-validation score: 77.53551912568307%

Trying model with 20 estimators...
Model accruacy on test set: 0.8157894736842105
Cross-validation score: 79.84699453551912%

Trying model with 30 estimators...
Model accruacy on test set: 0.8026315789473685
Cross-validation score: 82.1639344262295%

Trying model with 40 estimators...
Model accruacy on test set: 0.8289473684210527
Cross-validation score: 81.50273224043715%

Trying model with 50 estimators...
Model accruacy on test set: 0.8026315789473685
Cross-validation score: 81.84153005464483%

Trying model with 60 estimators...
Model accruacy on test set: 0.7894736842105263
Cross-validation score: 82.1584699453552%

Trying model with 70 estimators...
Model accruacy on test set: 0.7894736842105263
Cross-validation score: 80.85245901639342%

Trying model with 80 estimators...
Model accruacy on test set: 0.8157894736842105
Cross-validation score: 81.16393442622

## 6. Save model

In [25]:
# Python's pickle module

import pickle

# Save trained model to file
pickle.dump(model, open("random_forest_model1.pkl", "wb"))

In [26]:
# Load saved model 
loaded_model = pickle.load(open("random_forest_model1.pkl", "rb"))

#Make prediction on single sample
loaded_model.predict(np.array(X_test.loc[4]).reshape(1, -1))

array([1], dtype=int64)